#!/bin/bash

echo "🚀 Starting deployment process..."

# Navigate to React builder directory
cd resources/react-builder

# Build frontend
echo "📦 Building React frontend..."
npm run build:prod

if [ $? -ne 0 ]; then
    echo "❌ Build failed! Aborting deployment."
    exit 1
fi

# Navigate back to root
cd ../..

# Add built files to git
echo "📝 Adding built files to git..."
git add public/admin/
git add resources/views/admin.blade.php

# Check if there are changes to commit
if git diff --staged --quiet; then
    echo "ℹ️  No build changes to commit"
else
    echo "💾 Committing built assets..."
    git commit -m "Update frontend build assets

Auto-generated by deploy.sh script.
Compiled React frontend and updated blade view references."
fi

# Push to remote
echo "⬆️  Pushing to GitHub..."
git push

if [ $? -eq 0 ]; then
    echo "✅ Deployment successful!"
    echo ""
    echo "Your changes will be automatically deployed to the server via Plesk Git."
else
    echo "❌ Push failed! Check your git configuration."
    exit 1
fi
